default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: postgres
  pool: 10  # Adjust the pool size
  timeout: 5000

development:
  <<: *default
  database: test_app_dev

test:
  <<: *default
  database: test_app_test
