source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'json'
gem 'puma'
# New gems
gem "pg"    # for Postgres
gem "rake"  # so we can run Rake tasks
gem "sinatra-activerecord"    # for Active Record models
gem 'rack-test'
gem 'rspec'
gem 'pry'